### ISSUE TITLE
Todo list 1.20 update

### ISSUE THREAD

**Issue by KevinDaGame** [KevinDaGame/VoxelSniper-Reimagined#167]
https://minecraft.fandom.com/wiki/Java_Edition_1.20
- [x] Update Biomes list
- [x] Update Blocks list
- [x] Update treetype list
- [x] Update Entities list
- [x] Test brushes
- [ ] Migrate Forge beta
- [ ] Update forge getVersion()
