### ISSUE TITLE
Todo list Forge feature complete

### ISSUE THREAD

**Issue by Lennart99** [KevinDaGame/VoxelSniper-Reimagined#198]
Things we still need to do for Forge to be feature-complete (apart from probably some testing):
- [x] Implement Signs #197 
- [x] Implement ForgeBlockData::getCopy
- [x] Implement Leaves
- [x] Implement Waterlogged
- [x] Implement ForgeWorld::regenerateChunk
- [x] Cache world instead of creating new one (same as we do in spigot implementaion)
